databases:
  - name: servidorVictor
    plan: free
    databaseName: dbcine
    user: victor

services:
  - type: web
    plan: free
    name: cineUtc
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn cineUtc.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: servidorVictor
          property: externalConnectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: tesis-ej6i.onrender.com


# set DATABASE_URL=postgresql://victor:RTuE0lagjTJib2oO11Hqw5u487tMKBIJ@dpg-cqp29qqj1k6c73dbimmg-a.oregon-postgres.render.com/dbtesis_lzq1